export const workItems = [
 {slug:"flr-token-green-paper",year:"2018",title:"FLR-token Green Paper",client:"Working draft toward a Swiss regulator submission",summary:"A design for a token economy that pays every actor for verified restoration outcomes.",tags:["tokenisation","Bonn Challenge","mechanism design"]},
 {slug:"awd-blockchain-concept-note",year:"2016",title:"AWD monitoring on a decentralised network",client:"CCAFS / CGIAR",summary:"Smart sensors, farmer-owned data and third-party verification for climate finance in rice paddies.",tags:["IoT","MRV","Vietnam"]},
 {slug:"vietnam-low-carbon-rice-fund",year:"2016",title:"Vietnam Low Carbon Rice Fund",client:"CCAFS / Vietnam NDC investment plan",summary:"Outcome-based finance for alternate wetting and drying adoption at 500,000 hectares.",tags:["outcome finance","NDC","rice"]},
 {slug:"sierra-leone-gef-logframe",year:"2016",title:"Sierra Leone Western Peninsula logframe",client:"EBD Global Optimum / UNDP-GEF",summary:"A short technical draft reframing land-use stabilisation around finance and collaboration.",tags:["GEF","logframe","Sierra Leone"]},
 {slug:"fonerwa-gcf-presentation",year:"2016",title:"Agricultural Transformation: GCF funding proposal",client:"FONERWA, Kigali",summary:"A financing mechanism, farmer data platform and logistics infrastructure for Rwanda.",tags:["GCF","Rwanda","technology"]},
 {slug:"rwanda-flr-financing-final-report",year:"2016",title:"Financing mechanisms for Forest Landscape Restoration",client:"IUCN & ICRAF",summary:"Eight recommendations for an FLR fund, GCF strategy, technology platform and investment-readiness accelerator.",tags:["FLR fund","GCF","accelerator"]},
 {slug:"rwanda-restoration-fund-outline",year:"2015",title:"Towards a Rwanda Restoration Fund",client:"IUCN & ICRAF",summary:"The starting hypothesis: a layered fund as risk cushion for private investors, paired with a national PPP.",tags:["layered fund","PPP","Rwanda"]},
 {slug:"virgin-earth-challenge-entry",year:"2015",title:"The Virgin Earth Challenge — WeForest pre-entry",client:"WeForest",summary:"Reforestation as a gigatonne greenhouse-gas removal system, with country delivery and smallholder monitoring.",tags:["GGR","WeForest","Bonn Challenge"]},
 {slug:"climate-smart-lending-note",year:"2017",title:"Climate-smart lending platform on Stellar",client:"Personal note",summary:"A two-line fragment showing the direction of travel toward programmable, outcome-linked lending.",tags:["lending","Stellar"]}
] as const;
export const writingItems=[{slug:"what-i-got-wrong-about-the-flr-token",title:"What I got wrong about the FLR-token, and what I got right.",date:"2026",excerpt:"A candid re-read of the 2018 green paper: terminal value, verification and the parts that still hold."},{slug:"a-benefit-class-for-nature",title:"A benefit class for nature: first sketch of the receipt.",date:"2026",excerpt:"A worked example of a restoration receipt, from baseline polygon to threshold."},{slug:"we-have-all-the-money-in-the-world",title:"Ten years of ‘we have all the money in the world’.",date:"2026",excerpt:"Why the blended-finance decade underdelivered, and why the answer may be a monetary layer."}] as const;
export const institutionNames=["IUCN","ICRAF / World Agroforestry","CCAFS / CGIAR","WeForest","FONERWA","Bonn Challenge / GPFLR"];