export const workItems = [
 {slug:"restoration-token-design",year:"2018",title:"A restoration-linked monetary design",client:"Private working paper · publication restricted",summary:"A design for a token economy that pays actors for verified restoration outcomes. The underlying client paper is not published here.",tags:["tokenisation","Bonn Challenge","mechanism design"]},
 {slug:"smallholder-monitoring",year:"2016",title:"Smallholder monitoring and verification",client:"Private programme work · publication restricted",summary:"Smart sensors, farmer-owned data and third-party verification as a route to climate finance in rice systems.",tags:["IoT","MRV","smallholders"]},
 {slug:"low-carbon-rice-finance",year:"2016",title:"An outcome-based finance model for rice",client:"Private programme work · publication restricted",summary:"A fund and payment model for scaling water-management practice with measurable climate outcomes.",tags:["outcome finance","NDC","agriculture"]},
 {slug:"land-use-stabilisation",year:"2016",title:"Land-use stabilisation and stakeholder finance",client:"Private programme work · publication restricted",summary:"A technical approach to aligning land-use objectives, finance and institutional collaboration.",tags:["land use","logframe","collaboration"]},
 {slug:"agricultural-transformation",year:"2016",title:"Agricultural transformation and delivery infrastructure",client:"Private advisory work · publication restricted",summary:"A financing mechanism, farmer data platform and rural logistics concept for agricultural transformation.",tags:["GCF","data platform","technology"]},
 {slug:"forest-landscape-restoration-finance",year:"2016",title:"Forest landscape restoration finance",client:"Private advisory work · publication restricted",summary:"Recommendations for an FLR fund, public climate strategy, technology platform and investment-readiness accelerator.",tags:["FLR fund","catalytic capital","accelerator"]},
 {slug:"layered-restoration-fund",year:"2015",title:"A layered restoration fund",client:"Private advisory work · publication restricted",summary:"The hypothesis that a layered fund could cushion risk for private investors alongside a national partnership.",tags:["layered fund","PPP","restoration"]},
 {slug:"reforestation-delivery-model",year:"2015",title:"Reforestation as a large-scale delivery system",client:"Private strategy work · publication restricted",summary:"Reforestation framed as a climate and livelihoods system with country delivery and smallholder monitoring.",tags:["GGR","delivery","Bonn Challenge"]},
 {slug:"climate-smart-lending",year:"2017",title:"Climate-smart lending and programmable finance",client:"Private working note · publication restricted",summary:"A fragment showing the direction of travel toward programmable, outcome-linked lending.",tags:["lending","programmable finance"]}
] as const;
export const writingItems=[{slug:"what-i-got-wrong-about-the-flr-token",title:"What I got wrong about the FLR-token, and what I got right.",date:"2026",excerpt:"A candid re-read of the 2018 green paper: terminal value, verification and the parts that still hold."},{slug:"a-benefit-class-for-nature",title:"A benefit class for nature: first sketch of the receipt.",date:"2026",excerpt:"A worked example of a restoration receipt, from baseline polygon to threshold."},{slug:"we-have-all-the-money-in-the-world",title:"Ten years of ‘we have all the money in the world’.",date:"2026",excerpt:"Why the blended-finance decade underdelivered, and why the answer may be a monetary layer."}] as const;
export const institutionNames=["IUCN","ICRAF / World Agroforestry","CCAFS / CGIAR","WeForest","FONERWA","Bonn Challenge / GPFLR"];