import {SiteFooter,SiteHeader} from "@/components/SiteHeader";
const precedents=[
 ["Glow","A competitive subsidy model for a positive-externality industry.","Useful for thinking about additionality and recurring incentives; less suited to restoration where revenue is delayed or absent.","https://glow.org/"],
 ["Open Forest Protocol","Open measurement infrastructure for projects and ecological data.","Shows how open evidence can travel across projects; the institutional last mile remains outside the protocol.","https://www.openforestprotocol.org/"],
 ["Treegens","Proof-oriented tree restoration claims.","Makes the individual tree a legible unit of evidence; a national operating record needs to connect many such units to rights and payments.","https://treegens.org/"],
 ["Regen Network","On-chain ecological credit classes and project records.","Demonstrates ecological asset infrastructure, while the Champion proposal asks who carries national delivery responsibility.","https://www.regen.network/"],
 ["GainForest","Remote-sensing and community-linked forest incentives.","Shows the potential of accessible monitoring and local participation; scale still depends on durable institutions.","https://www.gainforest.earth/"],
 ["Arkreen","Distributed energy data and certificates.","A useful precedent for device data and automated rewards, though restoration has longer biological time horizons.","https://arkreen.com/"],
 ["Althelia / Moringa","Blended and impact investment in land-use outcomes.","The finance side of the problem: patient capital, aggregation and safeguards without assuming every project is bankable.","https://www.moringapartnership.com/"]
];
export const metadata={title:"Prior art — Net-Positive Solutions",description:"Public precedents in ecological measurement, outcome finance and restoration infrastructure."};
export default function PriorArt(){return <><SiteHeader/><main><section className="page-intro"><p className="eyebrow">Public prior art</p><h1>What exists already, and what it <em>does not solve.</em></h1><p>A curated directory of public projects and approaches. Links go to the source sites; this page does not republish their listings.</p></section><section className="work-list">{precedents.map(([name,what,lacks,url])=><article className="work-row" key={name}><span className="year">↗</span><div><h3><a href={url} target="_blank" rel="noreferrer">{name}</a></h3><p>{what}</p></div><div><p>{lacks}</p></div><a className="row-open" href={url} target="_blank" rel="noreferrer">Visit source</a></article>)}</section></main><SiteFooter/></>}