"use client";

import { useState } from "react";
import { ArrowDownRight, ArrowUpRight, BookOpen, ChevronRight, CircleCheck, ExternalLink, FileText, Menu, Network, ShieldCheck, Sprout, X } from "lucide-react";

const stakeholders = {
  "Public sector": { eyebrow: "01 / mandate + enabling conditions", title: "Make the landscape investable without making it extractive.", body: "Governments set the rules that determine whether long-horizon restoration capital can move: land and property rights, tax treatment, banking access, procurement, and credible public guarantees.", asks: ["Name a lead institution", "Publish a project pipeline", "De-risk the first loss"] },
  "Capital providers": { eyebrow: "02 / risk + return", title: "Match the instrument to the time horizon.", body: "Restoration does not produce a single cash flow. A blended, multi-layered system can pair patient public or catalytic capital with investors who need different return profiles.", asks: ["Price the full risk stack", "Fund readiness, not only assets", "Commit to 5–15 year horizons"] },
  "Landscape actors": { eyebrow: "03 / delivery + legitimacy", title: "Turn local knowledge into bankable evidence.", body: "Smallholders, forest-dependent people, women entrepreneurs, and local operators are not simply beneficiaries. They are delivery partners, data stewards, and value creators who need aggregation, assurance, and a meaningful role in governance.", asks: ["Aggregate viable projects", "Track social + ecological value", "Share decision rights"] },
};
type Stakeholder = keyof typeof stakeholders;

export default function Home() {
  const [activeStakeholder, setActiveStakeholder] = useState<Stakeholder>("Public sector");
  const [mobileMenu, setMobileMenu] = useState(false);
  return <main className="site-shell">
    <a className="skip-link" href="#main-content">Skip to content</a>
    <header className="topbar" data-design-id="topbar">
      <a className="brand" href="#top" data-design-id="brand-mark" aria-label="The Commons Reforestation Atlas home"><span className="brand-mark"><Sprout size={18} strokeWidth={1.7} /></span><span>THE COMMONS<br /><b>REFORESTATION ATLAS</b></span></a>
      <button className="menu-button" aria-label="Toggle navigation" onClick={() => setMobileMenu(!mobileMenu)}>{mobileMenu ? <X size={20} /> : <Menu size={20} />}</button>
      <nav className={`nav-links ${mobileMenu ? "is-open" : ""}`} aria-label="Primary navigation"><a href="#thesis" data-design-id="nav-thesis">The thesis</a><a href="#architecture" data-design-id="nav-architecture">Capital architecture</a><a href="#intelligent-internet" data-design-id="nav-intelligent-internet">II model</a><a href="#stakeholders" data-design-id="nav-stakeholders">Stakeholder map</a><a href="/atlas" data-design-id="nav-atlas">Atlas directory</a><a href="#research" data-design-id="nav-research">Research shelf</a><a className="nav-cta" href="#contribute" data-design-id="nav-contribute">Contribute <ArrowUpRight size={15} /></a></nav>
    </header>
    <div className="evidence-strip" data-design-id="evidence-strip"><span><span className="status-dot" /> Research track / working brief</span><span>Evidence base: FLIF 2017 · Fraser Brown profile claims · ii.inc model inquiry</span></div>
    <div id="main-content">
      <section className="hero" id="top" data-design-id="hero-section"><div className="hero-copy"><p className="kicker" data-design-id="hero-kicker">A field guide to financing living systems</p><h1 data-design-id="hero-title">Reforest the world.<br /><em>Redesign the rules.</em></h1><p className="hero-deck" data-design-id="hero-deck">What if the missing ingredient in global restoration is not another promise of capital — but a tokenomic architecture that treats the commons as an asset class with stewards, rights, and feedback loops?</p><div className="hero-actions"><a className="button button-primary" href="#thesis" data-design-id="hero-primary-cta">Enter the briefing <ChevronRight size={17} /></a><a className="text-link" href="#research" data-design-id="hero-secondary-cta">Read the sources <ArrowDownRight size={16} /></a></div><p className="micro-note" data-design-id="hero-note">An evolving research and communication track by ii.inc · September 2026</p></div><div className="hero-image-wrap" data-design-id="hero-image"><img src="/images/forest-restoration.png" alt="A restored forest corridor running through a dry landscape." /><div className="image-caption"><span>Restoration is a landscape-scale coordination problem.</span><span>01 / 09</span></div></div></section>
      <section className="signal-row" data-design-id="signal-row" aria-label="Key evidence"><div className="signal"><span className="signal-label">Annual need</span><strong>$36–49B</strong><span>to meet global restoration targets</span><span className="source-tag">FAO &amp; UNCCD, 2015</span></div><div className="signal"><span className="signal-label">AFR100 estimate</span><strong>$15B</strong><span>per year by 2030</span><span className="source-tag">FLIF 2017, p. 33</span></div><div className="signal"><span className="signal-label">Private plantation capital</span><strong>1%</strong><span>of developing-country investment in Africa (2011)</span><span className="source-tag">Castren, 2014</span></div></section>
      <section className="section thesis-section" id="thesis" data-design-id="thesis-section"><div className="section-intro"><p className="kicker">01 / the thesis</p><h2>The constraint is not only money.<br /><em>It is coordination.</em></h2></div><div className="thesis-body"><p className="lead">The 2017 Forest and Landscape Investment Forum made the gap plain: funds exist, but projects, investors, risk mitigants, and public institutions rarely meet in a shared operating system.</p><p>The deeper lesson is that finance must be designed around the work of restoration. Readiness, delivery, verification, payment, market access, and long-term stewardship are connected jobs — not separate projects to be handed from one institution to another.</p><p>That is the useful context for reading Fraser Brown’s pivot toward digital infrastructure and tokenomics. The question is not whether a token is fashionable. It is whether rules around value can make stewardship visible, participation legible, and shared outcomes governable.</p><div className="principle-note"><span className="principle-number">01</span><div><strong>Design the operating system before the instrument.</strong><p>A new fund is only useful when it connects policy, capital, delivery capacity, trusted evidence, and the people who create value on the ground.</p></div></div></div></section>
      <section className="dark-band" data-design-id="framing-band"><div><p className="kicker light">The 2017 pivot</p><h2>From “find the money”<br />to “design the system.”</h2></div><div className="band-note"><span className="band-number">→</span><p>Tokenomics is a design problem before it is a technology problem. The architecture has to answer: who creates value, who verifies it, who governs the rules, and who benefits over time?</p></div></section>
      <section className="section systems-section" data-design-id="systems-section"><div className="section-intro"><p className="kicker">01a / the operating system</p><h2>Capital is one layer.<br /><em>Trust is the stack.</em></h2><p className="intro-note">A restoration marketplace becomes useful when each layer reinforces the next.</p></div><div className="systems-grid"><article><span>01</span><h3>Policy + mandate</h3><p>Align national goals, public finance, land rights, and sector rules so that investment has somewhere legitimate to land.</p></article><article><span>02</span><h3>Readiness + aggregation</h3><p>Turn scattered opportunities into a pipeline with preparation support, local capacity, transaction design, and a clear route to market.</p></article><article><span>03</span><h3>Evidence + verification</h3><p>Combine field knowledge, sensors, remote observations, and accountable assurance into evidence that communities, governments, and investors can use.</p></article><article><span>04</span><h3>Rights + rewards</h3><p>Use digital agreements and tokenomic rules to record participation, distribute performance payments, and make value flows auditable.</p></article><article><span>05</span><h3>Stewardship + learning</h3><p>Keep finance moving after the first transaction: monitor outcomes, share feedback, and adapt rules as landscapes and livelihoods change.</p></article></div></section>
      <section className="section ii-section" id="intelligent-internet" data-design-id="intelligent-internet-section"><div className="section-intro"><p className="kicker">01b / the ii.inc model</p><h2>Make benefit<br /><em>the issuance rule.</em></h2><p className="intro-note">A public adaptation of the Intelligent Internet whitepaper for restoration finance.</p></div><div className="ii-content"><p className="lead">The whitepaper offers a candidate answer to the problem Fraser Brown has been pursuing: a network in which new value is issued when useful, verifiable work is done for the commons.</p><p>Its core loop is simple to state. A Foundation layer records a scarce global unit, Foundation Coins (FC). Validators earn issuance only by submitting a Proof-of-Benefit receipt for qualifying work. Local Culture layers let each country apply its own policy, data, and payment rules while remaining interoperable with the shared foundation. Personal agents and devices contribute work, context, and computation without surrendering all control to one platform.</p><div className="ii-loop" aria-label="The Intelligent Internet restoration loop"><div><span>01</span><strong>Define benefit</strong><small>Country and community goals become measurable work classes.</small></div><div><span>02</span><strong>Do the work</strong><small>Agents, people, sensors, and institutions deliver the work modules.</small></div><div><span>03</span><strong>Prove the work</strong><small>Receipts, provenance anchors, and independent replay make claims auditable.</small></div><div><span>04</span><strong>Route the value</strong><small>Issuance, grants, fees, and local credits reward contributors and infrastructure.</small></div></div></div></section>
      <section className="dark-band viability-band" data-design-id="viability-band"><div><p className="kicker light">Why it could scale</p><h2>One foundation.<br />Many local rooms.</h2></div><div className="band-note"><span className="band-number">↗</span><p>Restoration is globally urgent but locally governed. A shared settlement and provenance layer can standardise what must be trusted, while country layers preserve policy, language, data-residency, and delivery choices.</p></div><div className="viability-grid"><article><strong>Scale through repetition</strong><p>The same receipt, provenance, and work-module patterns can be reused across forests, farms, watersheds, coasts, and ocean monitoring.</p></article><article><strong>Scale through local ownership</strong><p>National nodes and Culture Credits create a route for ministries, communities, operators, and local markets to participate without flattening every jurisdiction into one model.</p></article><article><strong>Scale through lower friction</strong><p>Light-client proofs, shared data anchors, automated settlement, and agent orchestration can reduce duplicated verification and coordination costs.</p></article><article><strong>Scale through public goods</strong><p>A treasury that funds open datasets, training, tools, and infrastructure can widen the commons rather than only subsidising private transactions.</p></article></div></section>
      <section className="section architecture-section" id="architecture" data-design-id="architecture-section"><div className="section-intro"><p className="kicker">02 / capital architecture</p><h2>Three stages.<br /><em>Different capital.</em></h2><p className="intro-note">A sustainable investment pattern separates readiness, implementation, and the long tail of stewardship.</p></div><div className="architecture-content"><div className="stage-rail" aria-label="Three stages of restoration finance"><div className="stage stage-one"><span>01</span><div><h3>Readiness</h3><p>Up-front project design, transaction costs, baseline work, and the social license to proceed.</p></div><strong>Seed / catalytic</strong></div><div className="stage stage-two"><span>02</span><div><h3>Implementation</h3><p>Operational capital for planting, monitoring, livelihoods, and delivery capacity.</p></div><strong>Blended / growth</strong></div><div className="stage stage-three"><span>03</span><div><h3>Stewardship</h3><p>Long-term running costs and self-sustaining revenue as the landscape matures.</p></div><strong>Patient / recurring</strong></div></div><aside className="insight-card"><span className="insight-icon"><ShieldCheck size={21} /></span><p className="kicker">Design consideration</p><h3>Do not ask one instrument to do three jobs.</h3><p>Matching opportunities with the right investor matters: size, forest type, duration, and risk-sharing requirements vary.</p><a href="#research" className="text-link">See source trail <ArrowUpRight size={15} /></a></aside></div></section>
      <section className="stakeholder-section" id="stakeholders" data-design-id="stakeholder-section"><div className="section stakeholder-heading"><p className="kicker">03 / stakeholder map</p><h2>A commons model is<br /><em>a participation model.</em></h2><p>Move through the roles that have to align for the architecture to work. Each tab is an invitation to make the next question concrete.</p></div><div className="stakeholder-grid"><div className="stakeholder-tabs" role="tablist" aria-label="Stakeholder groups">{Object.keys(stakeholders).map((name) => <button key={name} className={activeStakeholder === name ? "active" : ""} onClick={() => setActiveStakeholder(name as Stakeholder)} role="tab" aria-selected={activeStakeholder === name}>{name}<ChevronRight size={16} /></button>)}</div><div className="stakeholder-panel" role="tabpanel"><p className="kicker">{stakeholders[activeStakeholder].eyebrow}</p><h3>{stakeholders[activeStakeholder].title}</h3><p>{stakeholders[activeStakeholder].body}</p><div className="asks"><p className="kicker">The immediate brief</p>{stakeholders[activeStakeholder].asks.map((ask) => <div key={ask}><CircleCheck size={16} /><span>{ask}</span></div>)}</div></div></div></section>
      <section className="section mechanism-section" data-design-id="mechanism-section"><div className="section-intro"><p className="kicker">04 / mechanism matrix</p><h2>De-risk the work.<br /><em>Keep the value shared.</em></h2></div><div className="matrix-wrap"><table><caption>Candidate risk mitigants for forest landscape restoration</caption><thead><tr><th scope="col">Mechanism</th><th scope="col">What it addresses</th><th scope="col">Structuring question</th></tr></thead><tbody><tr><th scope="row">Guarantees + credit enhancement</th><td>Perceived counterparty and project risk</td><td>Who bears first loss — and for how long?</td></tr><tr><th scope="row">Due diligence + assurance</th><td>Information gaps and valuation risk</td><td>Which evidence is trusted by all parties?</td></tr><tr><th scope="row">Portfolio diversification</th><td>Concentration and landscape variability</td><td>What is the unit of aggregation?</td></tr><tr><th scope="row">Insurance + securitization</th><td>Shock risk and liquidity constraints</td><td>Can future value be made financeable today?</td></tr><tr><th scope="row">Outcome-based payments</th><td>Adoption, performance, and accountability</td><td>What result triggers payment, and who controls the measure?</td></tr></tbody></table><p className="table-source">Source: FLIF 2017, pp. 17, 45. Mechanisms are presented as areas to explore, not as investment advice.</p></div></section>
      <section className="research-section" id="research" data-design-id="research-section"><div className="section research-heading"><p className="kicker light">05 / research shelf</p><h2>Start with evidence.<br /><em>Then make it useful.</em></h2><p>The public track separates established evidence from working hypotheses and turns both into practical questions for the next design cycle.</p></div><div className="source-grid"><a className="source-card" href="https://www.fao.org/fileadmin/user_upload/forest-landscape-restoration/docs/REPORT_FLIF_15092017.pdf" target="_blank" rel="noreferrer"><div className="source-top"><FileText size={19} /><span>Primary source · 2017</span><ExternalLink size={15} /></div><h3>Forest and Landscape Investment Forum report</h3><p>Financing needs, the three-stage investment pattern, risk mitigation, and the case for an investment platform.</p><span className="source-read">Open source <ArrowUpRight size={15} /></span></a><a className="source-card" href="https://ii.inc/whitepaper" target="_blank" rel="noreferrer"><div className="source-top"><Network size={19} /><span>Primary source · current</span><ExternalLink size={15} /></div><h3>The Intelligent Internet whitepaper</h3><p>Proof-of-Benefit, sovereign agents, local Culture layers, provenance anchors, and the treasury logic behind the proposed network.</p><span className="source-read">Open source <ArrowUpRight size={15} /></span></a><div className="source-card method-card"><div className="source-top"><BookOpen size={19} /><span>Next research sprint</span></div><h3>What we need to test next</h3><ul><li>Define restoration benefit classes and evidence standards.</li><li>Model country-layer economics, rights, safeguards, and verification costs.</li><li>Run a country pilot before making global scale claims.</li></ul><span className="source-read">Working agenda</span></div></div></section>
      <section className="closing-section" id="contribute" data-design-id="closing-section"><p className="kicker">The work continues</p><h2>Bring the missing<br /><em>stakeholder into the room.</em></h2><p>We are building the research track in public: reports, models, questions, and the practical planning needed to move from aspiration to shared infrastructure.</p><a className="button button-primary" href="mailto:research@ii.inc" data-design-id="closing-cta">Join the research track <ArrowUpRight size={16} /></a></section>
    </div>
    <footer className="footer" data-design-id="footer"><span>© 2026 ii.inc / Commons Reforestation Atlas</span><span>Built for the long horizon.</span><a href="#top">Back to top ↑</a></footer>
  </main>;
}