import Link from "next/link";
import { ArrowRight, BookOpen, Check, FileText } from "lucide-react";
import { SiteFooter, SiteHeader } from "@/components/SiteHeader";
import { institutionNames, writingItems } from "@/lib/content";

export default function Home() {
  return <><SiteHeader /><main>
    <section className="hero-new"><div><p className="eyebrow">Net-Positive Solutions / Fraser Brown</p><h1>Nature needs a <em>proof-of-benefit.</em></h1></div><div className="hero-copy-new"><p className="intro">For a decade I designed the funds, platforms and incentive systems meant to finance forest landscape restoration at Bonn Challenge scale.</p><p className="intro">The conclusion was uncomfortable: no financing mechanism existed that could do it. In 2018 I proposed one. The architecture now exists.</p><div className="hero-actions"><Link className="button button-amber" href="/thesis">Read the thesis <ArrowRight size={15} /></Link><Link className="text-link" href="/community">Join the community</Link></div><p className="small">This is a design proposal, not a token sale or a claim of endorsement. It is an invitation to put verified restoration inside an intelligence-backed monetary layer.</p></div></section>
    <section className="proof-strip"><article className="proof-card"><span className="year">2015 / MECHANISMS</span><h3>Rwanda FLR finance</h3><p>Fund design, GCF strategy, a technology platform and an accelerator for investment readiness.</p></article><article className="proof-card"><span className="year">2016 / VERIFICATION</span><h3>Vietnam AWD</h3><p>Smart sensors and a blockchain model to make methane reductions verifiable and payable to smallholders.</p></article><article className="proof-card"><span className="year">2018 / CAPITAL</span><h3>The FLR-token</h3><p>A green paper for a currency whose issuance and payout were bound to proven restoration outcomes.</p></article></section>
    <section className="section-wrap two-col"><div><p className="eyebrow">The through-line</p><h2>Partial answers.<br /><em>One missing layer.</em></h2></div><div className="reading"><p className="lead">Each project solved one part of the problem. None solved the underlying monetary question: how do you reward public benefit at the scale and duration that nature requires?</p><p>The Intelligent Internet whitepaper describes currency created only when validators attach cryptographic evidence that useful work was done for the commons. Its first benefit classes are compute, training and data curation. It leaves the door open for others.</p><p>Verified restoration — trees alive at coordinates, hectares under regeneration, water tables measured, methane avoided — is the benefit class I believe the architecture is missing.</p><Link className="text-link" href="/thesis">Read the full argument →</Link></div></section>
    <div className="note-band"><p>“Financial return is fundamentally different to economic return.”</p><Link className="button" href="/work">Explore the archive</Link></div>
    <section className="institution-strip">{institutionNames.map((name) => <span key={name}>{name}</span>)}</section>
    <section className="section-wrap"><div className="two-col"><div><p className="eyebrow">Latest writing</p><h2>Notes from the<br /><em>working edge.</em></h2></div><div><div className="latest-grid">{writingItems.map((item) => <Link className="card" href={`/writing/${item.slug}`} key={item.slug}><span className="meta">{item.date} · note</span><h3>{item.title}</h3><p>{item.excerpt}</p><span className="text-link">Read note →</span></Link>)}</div></div></div></section>
    <section className="section-wrap" style={{paddingTop:0}}><div className="callout"><p className="eyebrow">A serious proposal needs receipts</p><h2>Read the documents behind the argument.</h2><p className="reading">The archive is a record of trying to solve one problem from different angles — funds, platforms, verification and incentives. It includes working drafts and honest limits.</p><Link className="button" href="/work"><FileText size={15} /> Open the work archive</Link></div></section>
    <section className="section-wrap two-col" style={{background:"#202622",color:"#f1ede5"}}><div><p className="eyebrow" style={{color:"#e7a35f"}}>The invitation</p><h2>Who should get<br /><em>in touch?</em></h2></div><div className="reading" style={{color:"#c8cbc3"}}><p>Restoration implementers with measured outcomes. MRV technologists. People building on or near the Intelligent Internet stack. Funders interested in outcome-based nature finance.</p><Link className="button button-amber" href="/contact">Start a conversation <ArrowRight size={15} /></Link></div></section>
  </main><SiteFooter /></>;
}